[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=61",
]

[project]
name = "wavelet_prosody_toolkit"
version = "1.1.0"
authors = [
  {name="Antti Suni", email="antti.suni@helsinki.fi"},
  {name="Sébastien Le Maguer", email="sebastien.lemaguer@helsinki.fi"}
]
description = "Prosody wavelet analysis toolkit"
readme = {file="README.rst", content-type="text/x-rst"}
requires-python='>=3.11'
classifiers = [
  'Development Status :: 4 - Beta',
  # Audience
  'Intended Audience :: Science/Research',
  # Topics
  'Topic :: Multimedia :: Sound/Audio :: Speech',
  'Topic :: Scientific/Engineering :: Information Analysis',
  'Topic :: Scientific/Engineering :: Visualization',
  # Pick your license as you wish
  'License :: OSI Approved :: MIT License',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.11',
  'Programming Language :: Python :: 3.12',
  'Programming Language :: Python :: 3.13',
  'Programming Language :: Python :: 3.14',
]
dependencies = [
  "pyyaml>=6.0.3",
  "pycwt>=0.5.0b0",
  "numpy>=2.4.6",
  "scipy>=1.12",
  "soundfile>=0.14.0",
  "tgt>=1.5",
  "wavio>=0.0.9",
  "joblib>=1.6.0"
]

[project.optional-dependencies]
gui = [
  "pyside6>=6.11.2",
  "matplotlib>=3.11.2"
]
reaper = [
  "pyreaper>=0.0.11"
]
docs = [
  "sphinx>=9.0",
  "sphinx_rtd_theme>=3.1.0",
  "numpydoc>=1.11.0"
]
dev = [
  "pre-commit"
]


[project.scripts]
prosody_labeller = "wavelet_prosody_toolkit.prosody_labeller:main"
cwt_analysis_synthesis = "wavelet_prosody_toolkit.cwt_analysis_synthesis:main"
cwt_global_spectrum = "wavelet_prosody_toolkit.cwt_global_spectrum:main"
wavelet_gui = "wavelet_prosody_toolkit.wavelet_gui:main"

[project.urls]
Homepage = "https://github.com/asuni/wavelet_prosody_toolkit"
Issues = "https://github.com/asuni/wavelet_prosody_toolkit/issues"
git = "https://github.com/asuni/wavelet_prosody_toolkit.git"

[tool.setuptools]
packages = ["wavelet_prosody_toolkit"]

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |Dockerfile
  |Jenkinfile
)/
'''

[tool.flake8]
max-line-length = 120

[tool.basedpyright]
typeCheckingMode = "standard"
