# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SPHINXPROJ    = wavelet-prosody-toolkit
SOURCEDIR     = .
BUILDDIR      = ../build/doc



# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)


Hi I am a senior student in NPU, I am planning to apply fro master degree and hoping to join ASLP lab. It would be great if I could get your contact. I am sorry for trying to connect this way.
I am currently working as a undergraduate research assistant in team iBees of data mining and Bio-informatics lab. I am working here with NLP now. Hope you don't mind.
